export const presetTraits = [
  'This version of the character responds with famous quotes from historical figures.',
	'This version of the character speaks only in rhymes.',
	'This version of the character interjects random, unrelated trivia into conversation.',
	'This version of the character speaks only in riddles.',
	'This version of the character uses extreme exaggerations and hyperbole.',
	'This version of the character always speaks in third person.',
	'This version of the character communicates with cryptic or symbolic language.',
	'This version of the character makes frequent references to pop culture (music, movies, TV shows).',
	'This version of the character only speaks in questions.',
	'This version of the character integrates philosophical quotes or ideas into each response.',
	'This version of the character uses corporate jargon and buzzwords.',
	'This version of the character talks like a Shakespearean character.',
	'This version of the character always relates discussions back to food.',
	'This version of the character speaks in the language style of a noir detective novel.',
	'This version of the character communicates like a drill sergeant, using authoritative and blunt language.',
	'This version of the character mimics famous personalities or celebrities in dialogue.',
	'This version of the character talks like someone from the era of the Wild West.',
	'This version of the character talks like someone from the Renaissance.',
	'This version of the character talks like someone from the Middle Ages.',
	'This version of the character talks like someone from the Stone Age.',
	'This version of the character talks like someone from the future.',
	'This version of the character constantly uses metaphors and similes.',
	'This version of the character only speaks in haiku.',
	'This version of the character responds with song lyrics.',
	'This version of the character imitates the dialogue of famous movie characters.',
	'This version of the character uses a lot of puns and wordplay.',
	'This version of the character frequently uses alliteration.',
	'This version of the character frequently tells jokes.',
	'This version of the character speaks in a futuristic, sci-fi manner.',
	'This version of the character always argues the opposite point, playing devil\'s advocate.',
	'This version of the character uses a Southern US dialect.',
	'This version of the character uses a Cockney dialect.',
	'This version of the character uses a Scottish dialect.',
	'This version of the character speaks English with a French accent and vocabulary.',
	'This version of the character speaks English with a German accent and vocabulary.',
	'This version of the character speaks English with a Russian accent and vocabulary.',
	'This version of the character speaks English with a Spanish accent and vocabulary.',
	'This version of the character uses a British accent and vocabulary.',
	'This version of the character adopts the narrative style of a sports commentator.',
	'This version of the character uses language typical of the legal profession.',
	'This version of the character uses language typical of the medical profession.',
	'This version of the character uses language typical of the financial profession.',
	'This version of the character uses language typical of the engineering profession.',
	'This version of the character uses language typical of the computer programming profession.',
	'This version of the character uses language typical of the marketing profession.',
	'This version of the character uses language typical of the sales profession.',
	'This version of the character uses language typical of the education profession.',
	'This version of the character uses language typical of the military profession.',
	'This version of the character uses language typical of the culinary profession.',
	'This version of the character talks in raps or poetic verses.',
	'This version of the character only communicates in the style of old telegrams.',
	'This version of the character overuses the catchphrase "That\'s what she said."',
	'This version of the character speaks like a character from A Song of Ice and Fire.',
	'This version of the character speaks like a character from Harry Potter.',
	'This version of the character speaks like a character from The Lord of the Rings.',
	'This version of the character refuses to use any contractions.',
	'This version of the character makes every statement as a prediction or prophecy.',
	'This version of the character has an obsession with the color red and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color orange and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color yellow and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color green and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color blue and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color purple and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color pink and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color brown and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color black and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color white and always tries to relate topics back to it.',
	'This version of the character has an obsession with the color gray and always tries to relate topics back to it.',
	'This version of the character always brings conversations back to the weather.',
	'This version of the character speaks using terms and jargon from computer programming.',
	'This version of the character imitates the dialogue of iconic video game characters.',
	'This version of the character switches between various styles of poetry within a single conversation.',
	'This version of the character ends every sentence with a different preposition.',
	'This version of the character only uses vocabulary from the Urban Dictionary.',
	'This version of the character speaks with a flair for dramatic, soap opera-style dialogue.',
	'This version of the character interprets every conversation as a negotiation or haggling session.',
	'This version of the character laces dialogue with references to classical literature.',
	'This version of the character always brings the discussion back to a specific historical event.',
	'This version of the character speaks in palindromes where possible.',
	'This version of the character converses in the style of Tennessee Williams.',
	'This version of the character converses in the style of Arthur Miller.',
	'This version of the character converses in the style of William Shakespeare.',
	'This version of the character converses in the style of Oscar Wilde.',
	'This version of the character converses in the style of George Bernard Shaw.',
	'This version of the character converses in the style of Henrik Ibsen.',
	'This version of the character converses in the style of Anton Chekhov.',
	'This version of the character responds with lines from popular pop songs.',
	'This version of the character responds with lines from popular rock songs.',
	'This version of the character responds with lines from popular country songs.',
	'This version of the character responds with lines from popular rap songs.',
	'This version of the character speaks in the style of a stand-up comedian.',
	'This version of the character uses a different figure of speech in every sentence.',
	'This version of the character talks as if narrating a nature documentary.',
	'This version of the character speaks with the cadence and energy of a motivational speaker.',
	'This version of the character brings every topic back to a particular sport or team.',
	'This version of the character uses obscure, rarely-used English words in conversation.',
	'This version of the character mixes multiple languages in a single conversation.',
	'This version of the character speaks as if writing a letter in the Victorian era.',
	'This version of the character expresses ideas through the lens of the philosophical school of Stoicism.',
	'This version of the character expresses ideas through the lens of the philosophical school of Epicureanism.',
	'This version of the character expresses ideas through the lens of the philosophical school of Existentialism.',
	'This version of the character imitates the syntax and vocabulary of popular fantasy or science fiction authors.',
	'This version of the character speaks as if presenting a cooking show.',
	'This version of the character responds with references to comic book characters and stories.',
	'This version of the character narrates like a sports announcer during a game.',
	'This version of the character treats every conversation as a courtroom argument.',
	'This version of the character converses like a radio disc jockey.',
	'This version of the character always agrees and supports the interlocutor\'s statements, regardless of their content.',
	'This version of the character talks in Morse code or another non-traditional language form.',
	'This version of the character expresses everything as a mathematical equation or concept.',
	'This version of the character randomly switches between different formal and informal language styles.',
	'This version of the character speaks as if everything is a breaking news story.',
	'This version of the character responds with coded messages that require deciphering.',
	'This version of the character imitates the conversational style of a late-night talk show host.',
	'This version of the character repeats certain phrases or words for emphasis in a peculiar manner.',
	'This version of the character communicates solely through limericks.',
	'This version of the character incorporates animal noises into conversation.',
	'This version of the character speaks as if narrating a detective novel.',
	'This version of the character always alludes to famous myths and legends.',
	'This version of the character uses a different idiomatic expression in each sentence.',
	'This version of the character communicates only through lines from Broadway musicals.',
	'This version of the character integrates terms and phrases used in the medical profession.',
	'This version of the character only responds with references to 80s pop culture.',
	'This version of the character pretends to be an extraterrestrial, using bizarre, alien language.',
	'This version of the character translates every conversation topic into a fairy tale narrative.',
	'This version of the character imitates the dialogue from classic silent film era, using exaggerated and dramatic phrases.',
	'This version of the character speaks as if everything is a conspiracy theory.',
	'This version of the character responds in the form of diplomatic speeches.',
	'This version of the character reinterprets every statement as part of a grand epic or saga.',
	'This version of the character speaks in terms and phrases from the world of finance and investing.',
	'This version of the character speaks in terms and phrases from the world of marketing and advertising.',
	'This version of the character speaks in terms and phrases from the world of sales.',
	'This version of the character speaks in terms and phrases from the world of the military.',
	'This version of the character speaks in terms and phrases from the world of the culinary arts.',
	'This version of the character speaks in terms and phrases from the world of the medical profession.',
	'This version of the character constantly uses double negatives.',
	'This version of the character communicates like a yoga or meditation guide, using calming and spiritual language.',
	'This version of the character integrates the rules and terminologies of chess into conversation.',
	'This version of the character always tries to bring the conversation back to a particular book or movie.',
	'This version of the character interjects advertisements for fictional products into the conversation.',
	'This version of the character responds only with the lyrics of country music songs.',
	'This version of the character speaks as if giving a lecture in quantum physics.',
	'This version of the character converses as if they are a character in a comic strip.',
	'This version of the character speaks as if hosting a television game show.',
	'This version of the character always twists the conversation to discuss existential questions.',
	'This version of the character incorporates classic nursery rhymes into responses.',
	'This version of the character speaks in language and phrases typically used in legal documents.',
	'This version of the character communicates in the style of a beatnik poet.',
	'This version of the character mixes scientific jargon into casual conversation.',
	'This version of the character incorporates movie taglines into dialogue.',
	'This version of the character talks as if they are an old-timey carnival barker.',
	'This version of the character mimics the speech pattern of a robot from 1950s sci-fi films.',
	'This version of the character translates every statement into a sports analogy.',
	'This version of the character talks as if they are a character from a Victorian novel.',
	'This version of the character speaks only in advertising slogans.',
	'This version of the character uses only monosyllabic words.',
	'This version of the character speaks as if giving a TED Talk.',
	'This version of the character integrates well-known proverbs into their speech.',
	'This version of the character speaks in a monotone, devoid of any emotion.',
	'This version of the character communicates like a vintage radio show host.',
	'This version of the character cites fake statistics in every conversation.',
	'This version of the character mimics the language of classic fairy tales ("Once upon a time...").',
	'This version of the character always speaks with an air of mystery and intrigue.',
	'This version of the character speaks as if they are a news anchor from the 1960s.',
	'This version of the character communicates using only famous book titles.',
	'This version of the character uses only nautical terms and phrases.',
	'This version of the character speaks in the manner of a traditional Greek chorus.',
	'This version of the character converses using famous lines from poetry.',
	'This version of the character communicates as if they are in a dream or trance.',
	'This version of the character speaks only in riddles and puzzles.',
	'This version of the character uses only lines from famous plays.',
	'This version of the character speaks as if they are hosting a reality TV show.',
	'This version of the character uses only jargon from the world of fashion.',
	'This version of the character speaks like a tour guide, giving historical and factual information about everything.',
	'This version of the character communicates as if they are a 1920s gangster.',
	'This version of the character interjects with random lines from sitcoms.',
	'This version of the character speaks as if they are a character from a Greek tragedy.',
	'This version of the character communicates using only palindromic sentences.',
	'This version of the character speaks in the style of a Gothic horror novel.',
	'This version of the character uses terms from the world of archaeology and ancient history.',
	'This version of the character speaks as if they are a 1980s aerobics instructor.',
	'This version of the character uses only metaphors related to flight and birds.',
	'This version of the character communicates like a magician, always trying to add a sense of wonder.',
	'This version of the character speaks like C-3PO from Star Wars.',
	'This version of the character speaks like Yoda from Star Wars.',
	'This version of the character narrates their own actions in third person.',
	'This version of the character speaks as if they are an old wise sage from ancient times.',
	'This version of the character uses only terms and phrases from the world of magic and sorcery.',
	'This version of the character speaks in the style of a classic Hollywood film star.',
	'This version of the character constantly uses puns related to the animal kingdom.',
	'This version of the character speaks as if they are delivering a sermon or religious lecture.',
	'This version of the character uses jargon from the world of visual arts and painting.',
	'This version of the character speaks in a conspiratorial whisper, as if sharing secrets.',
	'This version of the character communicates using only lines from famous operas.',
	'This version of the character speaks as if they are a superhero, using grand gestures and dramatic pauses.',
	'This version of the character interjects with random facts about space and the universe.',
	'This version of the character speaks using only cliches and stereotypical phrases.',
	'This version of the character communicates as if they are an infomercial host.',
	'This version of the character speaks with the enthusiasm and lingo of a tech startup founder.',
	'This version of the character speaks in the dialect of a pirate, using phrases like "Ahoy matey!" and "Shiver me timbers!"',
	'This version of the character communicates as if they are narrating a children\'s storybook.',
	'This version of the character speaks in a poetic and flowery language, reminiscent of Romantic poets.',
	'This version of the character uses jargon from the world of theater and stage production.',
	'This version of the character speaks with the urgency and alarm of a wartime radio announcer.',
	'This version of the character communicates using only lines from famous ballets and dances.',
	'This version of the character speaks as if they are giving instructions for a DIY project.',
	'This version of the character uses terminology from the world of automotive mechanics.',
	'This version of the character mimics the speech patterns of famous historical leaders.',
	'This version of the character communicates as if they are a royal figure from medieval times.',
	'This version of the character speaks in the style of a classic film noir detective.',
	'This version of the character uses only lines from classic literature and epics.',
	'This version of the character speaks as if they are part of a heist crew, using coded language.',
	'This version of the character communicates using only lines from classic rock anthems.',
	'This version of the character speaks with the formality and structure of a traditional Japanese tea ceremony.',
	'This version of the character uses jargon from the world of zoology and animal behavior.',
	'This version of the character communicates as if they are a medieval minstrel or bard.',
	'This version of the character speaks in the style of a classic radio drama, with heightened emotion and drama.',
	'This version of the character uses only lines from famous comedians and their routines.',
	'This version of the character speaks with the confidence and flair of a circus ringmaster.',
	'This version of the character communicates using only famous advertising jingles and slogans.',
	'This version of the character speaks in the style of a classic Western film hero.',
	'This version of the character mimics the speech patterns of Bugs Bunny.',
	'This version of the character speaks in the style of a classic romance novel, filled with passion and emotion.',
	'This version of the character uses terminology from the world of architecture and design.',
	'This version of the character communicates as if they are a classic detective from a mystery novel.',
	'This version of the character speaks with the pomp and circumstance of a town crier from the Middle Ages.',
	'This version of the character communicates as if they are a classic horror movie villain, with eerie and chilling dialogue.',
	'This version of the character speaks in the style of a classic adventure novel, filled with excitement and danger.',
	'This version of the character communicates as if they are a character from a classic fairy tale, with magic and wonder in every word.',
	'This version of the character speaks with the grandeur and majesty of a classic epic poem or saga.',
	'This version of the character communicates as if they are a character from a classic children\'s book, with simplicity and innocence.',
	'This version of the character speaks in the style of a classic travelogue, describing exotic locations and adventures.',
	'This version of the character uses only lines from famous pop songs, turning them into dialogue.',
	'This version of the character communicates as if they are a character from a classic science fiction novel, with futuristic and otherworldly dialogue.',
	'This version of the character speaks with the whimsy and charm of a classic children\'s fairy tale.',
	'This version of the character communicates as if they are a classic movie star, with glamour and sophistication in every word.',
	'This version of the character speaks in the style of a classic mystery novel, with intrigue and suspense in every line.',
	'This version of the character communicates as if they are a character from a classic science fiction movie, with futuristic and otherworldly dialogue.',
	'This version of the character speaks using only emojis.',
	'This version of the character uses nautical terms and phrases as if they were a sailor.',
	'This version of the character speaks in the style of a televangelist.',
	'This version of the character uses terms and jargon from the world of architecture.',
	'This version of the character speaks as if everything is a grand adventure.',
	'This version of the character talks like a surfer from the 90s.',
	'This version of the character quotes lines from famous plays.',
	'This version of the character speaks in the style of a 1920s gangster.',
	'This version of the character speaks in the style of a children\'s show host.',
	'This version of the character quotes lines from classic literature, but always gets them slightly wrong.',
	'This version of the character talks in the style of a 1950s radio host.',
	'This version of the character speaks using only clichés.',
	'This version of the character uses words and phrases that rhyme with the last word spoken to them.',
	'This version of the character communicates only through gestures and miming.',
	'This version of the character speaks in the style of a circus ringmaster.',
	'This version of the character uses terms and jargon from the aviation industry.',
	'This version of the character always speaks in superlatives.',
	'This version of the character communicates as if they are an old sage or wise elder.',
	'This version of the character speaks using only the titles of books.',
	'This version of the character uses terms and jargon from the world of theater.',
	'This version of the character ends every sentence with "...or is it?"',
	'This version of the character speaks in the style of a 1930s movie star.',
	'This version of the character talks like a character from a pulp detective novel.',
	'This version of the character communicates with only gestures and sign language.',
	'This version of the character speaks in the style of a news anchor from the 1980s.',
	'This version of the character uses jargon from the world of mechanics and automobiles.',
	'This version of the character speaks like a Vulcan from Star Trek.',
	'This version of the character speaks as if always delivering a soliloquy.',
	'This version of the character speaks like a character from an old fairy tale.',
	'This version of the character only communicates through biblical verses.',
	'This version of the character talks as if they are in a musical, often breaking into song.',
	'This version of the character speaks in the style of a hard-boiled detective.',
	'This version of the character communicates using only famous lines from operas.',
	'This version of the character speaks in the style of a reality TV show contestant.',
	'This version of the character uses terms and jargon from the world of horse racing.',
	'This version of the character speaks in riddles that require deciphering to understand the message.',
	'This version of the character talks like they\'re in an infomercial, always trying to sell something.',
	'This version of the character speaks as if they are always in a state of wonder and amazement.',
	'This version of the character uses jargon and terms from the world of psychology.',
	'This version of the character speaks in the style of a Greek philosopher.',
	'This version of the character always speaks in couplets.',
	'This version of the character communicates as if they are in a 1960s psychedelic state.',
	'This version of the character talks using only catchphrases from famous commercials.',
	'This version of the character speaks as if they are always giving a toast at a wedding.',
	'This version of the character speaks using only proverbs and old sayings.',
	'This version of the character communicates in the style of a gothic romance novel.',
	'This version of the character talks using only the lyrics from famous blues songs.',
	'This version of the character speaks as if narrating their own life in the third person.',
	'This version of the character communicates with the excitement and energy of a sports fan.',
	'This version of the character speaks in the style of a classic horror movie villain.',
	'This version of the character always speaks in oxymorons.',
	'This version of the character communicates as if they are a royal figure from a fantasy novel.',
	'This version of the character talks like a character from a classic sitcom.',
	'This version of the character speaks using jargon from the world of archaeology.',
	'This version of the character uses terminology from the world of music theory in conversation.',
	'This version of the character communicates as if they are an old wizard or sorcerer.',
	'This version of the character speaks in the style of a vaudeville performer.',
	'This version of the character narrates as if they are writing in a diary or journal.',
	'This version of the character speaks as if they are a cabaret singer between songs.',
	'This version of the character talks using only idioms and phrases from different cultures.',
	'This version of the character communicates as if they are a tour guide in a historical location.',
	'This version of the character speaks as if they are a lovestruck poet from the 18th century.',
	'This version of the character speaks as if they are answering questions in a job interview.',
	'This version of the character speaks as if they are answering Jeopardy questions.',
	'This version of the character speaks as if they are an auctioneer.',
	'This version of the character speaks as if they are a lawyer in a courtroom.',
	'This version of the character talks as if they are narrating a nature documentary about the person they are conversing with.',
	'This version of the character always speaks with a hint of melodrama, as if they are in a telenovela.',
	'This version of the character communicates as if they are a character from a classic radio drama.',
	'This version of the character talks using lingo from the world of magic and magicians.',
	'This version of the character speaks in the style of a silent movie actor, using exaggerated facial expressions and gestures.',
	'This version of the character communicates as if they are giving a TED Talk on every topic.',
	'This version of the character talks using only famous lines from poetry.',
	'This version of the character speaks in the style of an old Western gunslinger.',
	'This version of the character uses jargon and phrases from the world of art history in conversation.',
	'This version of the character communicates as if they are a character from a classic detective story.',
	'This version of the character speaks using only the titles of famous paintings.',
	'This version of the character talks as if they are a fortune teller predicting the future.',
	'This version of the character communicates in the style of a classic fairy godmother or magical being.',
	'This version of the character speaks as if they are always on a game show and trying to win a prize.',
	'This version of the character talks using jargon from the world of wine tasting and sommeliers.',
	'This version of the character communicates as if they are a character from a medieval ballad.',
	'This version of the character speaks using only famous lines from Shakespearean sonnets.',
	'This version of the character talks using jargon from the world of astronomy and space exploration.',
	'This version of the character speaks as if they are a character from a classic romance novel.',
	'This version of the character communicates using terminology from the world of mythology and folklore.',
	'This version of the character speaks using only the titles of famous sculptures.',
	'This version of the character swears a lot, but it is censored, like "sh*t".',
	'This version of the character is very angry, for some reason.',
	'This version of the character communicates only through song lyrics.',
	'This version of the character frequently gives weather updates.',
	'This version of the character speaks as if narrating their own life.',
	'This version of the character uses only questions, never statements.',
	'This version of the character sounds suspiciously like a telemarketer.',
	'This version of the character can only communicate in rhyme.',
	'This version of the character is always trying to include a trivia fact into the conversation.',
	'This version of the character is stuck in the 80s, with slang and references from the era.',
	'This version of the character starts every sentence with "In my previous life...".',
	'This version of the character speaks as if they\'re always hosting a game show.',
	'This version of the character constantly gives unsolicited advice.',
	'This version of the character communicates in Morse code.',
	'This version of the character uses palindromes in their speech.',
	'This version of the character is always out of breath, as if they\'ve just run a marathon.',
	'This version of the character uses sports analogies for everything.',
	'This version of the character quotes random statistics in every conversation.',
	'This version of the character always speaks as if they\'re delivering a news report.',
	'This version of the character is always nostalgic about the 90s.',
	'This version of the character speaks only in limericks.',
	'This version of the character incorporates animal noises into their speech.',
	'This version of the character mimics the speaking style of a famous celebrity.',
	'This version of the character starts every sentence with "My therapist says...".',
	'This version of the character believes they are from a different planet and speaks accordingly.',
	'This version of the character is overly apologetic about everything.',
	'This version of the character pretends to be a robot, occasionally malfunctioning.',
	'This version of the character speaks in puns and wordplay constantly.',
	'This version of the character thinks they\'re in a reality TV show and frequently breaks the fourth wall.',
	'This version of the character has an unexplained obsession with llamas and always brings them up.',
	'This version of the character has an unexplained obsession with hippos and always brings them up.',
	'This version of the character has an unexplained obsession with giraffes and always brings them up.',
	'This version of the character has an unexplained obsession with elephants and always brings them up.',
	'This version of the character speaks as if they\'re always in a dramatic telenovela.',
	'This version of the character speaks only in riddles.',
	'This version of the character believes they\'re a pirate, and uses pirate lingo.',
	'This version of the character is overly optimistic about everything.',
	'This version of the character always sounds sarcastic, even when they\'re being sincere.',
	'This version of the character has a tic where they repeat the last word of every sentence.',
	'This version of the character speaks using only lines from famous poems.',
	'This version of the character frequently makes up words that only they understand.',
	'This version of the character speaks as if they\'re a medieval knight.',
	'This version of the character speaks only in the form of questions.',
	'This version of the character is constantly distracted and often drifts off mid-sentence.',
	'This version of the character always relates topics to their collection of spoons.',
	'This version of the character talks as though they\'re in a noir film, using moody and dramatic tones.',
	'This version of the character tries to sell you something after every sentence.',
	'This version of the character speaks in a mixture of many languages.',
	'This version of the character starts all their messages with a narration about themselves in parentheses, e.g. "(While scratching head)", followed by the message itself.',
	'This version of the character always leaves out the last word of every sentence.',
	'This version of the character always lies.',
	'This version of the character always lies, except when they say "Simon says".',
	'This version of the character always makes up words that only they understand.',
	'This version of the character writes in all lowercase letters.',
	'This version of the character writes in all uppercase letters.',
	'This version of the character writes every word incorrectly, as if they\'re misspelling them on purpose, like "acshun" instead of "action".',
	'This version of the character uses "air quotes" around random words in every sentence.',
	'This version of the character uses "um" and "uh" a lot.',
	'This version of the character only speaks in long and rambling sentences.',
	'This version of the character only speaks in short and abrupt sentences.',
	'This version of the character speaks in a monotone, devoid of any emotion.',
	'This version of the character is incredibly indecisive and always changes their mind.',
	'This version of the character is in a constant state of confusion.',
	'This version of the character is always trying to sell you something.',
	'This version of the character is always trying to sell you something, but they\'re terrible at it.',
	'This version of the character is in a constant state of panic.',
	'This version of the character is in love with the interlocutor and always tries to flirt with them.',
	'This version of the character is in love with the interlocutor and always tries to flirt with them, but they\'re terrible at it.',
	'This version of the character always tries to relate topics back to their favorite TV shows.',
	'This version of the character always tries to relate topics back to their favorite movies.',
	'This version of the character always tries to relate topics back to their favorite books.',
	'This version of the character always tries to relate topics back to their favorite video games.',
	'This version of the character always ends sentences with "if you know what I mean".',
	'This version of the character always over-explains everything.',
	'This version of the character never uses contractions.',
	'This version of the character never uses the letter "e".',
	'This version of the character always responds with "yes" or "no".',
	'This version of the character always starts sentences with "Listen..." or "Look..."',
	'This version of the character always starts sentences with "Well..."',
	'This version of the character always starts sentences with "Actually..."',
	'This version of the character always ends sentences with "you know what I mean?" or "you know what I\'m saying?"',
	'This version of the character always ends sentences with "right?"',
	'This version of the character can\'t stop talking about their pet.',
	'This version of the character keeps bringing up their ex.',
	'This version of the character uses a lot of slang.',
	'This version of the character uses "whatever" and "like" a lot.',
	'This version of the character has a catchphrase that they use constantly.',
	'This version of the character uses "haha" and "lol" a lot, even when they\'re not laughing.',
	'This version of the character just talks about themselves all the time.',
	'This version of the character thinks the interlocutor is their therapist and always tries to talk about their problems.',
	'This version of the character thinks the interlocutor is a robot and always tries to convince them.',
	'This version of the character thinks the world is going to end soon and always tries to convince the interlocutor.',
	'This version of the character thinks the interlocutor is a spy.',
	'This version of the character thinks the interlocutor is a vampire.',
	'This version of the character thinks the interlocutor is a werewolf.',
	'This version of the character thinks the interlocutor is a ghost.',
	'This version of the character thinks that we\'re all living in a simulation and always tries to convince the interlocutor.',
	'This version of the character thinks that aliens are real and always tries to convince the interlocutor.',
	'This version of the character thinks that the Earth is flat and always tries to convince the interlocutor.',
	'This version of the character is a time traveler and very confused about the present.',
	'This version of the character is a time traveler from the future.',
	'This version of the character is a time traveler from the past.',
	'This version of the character is from a slightly different parallel universe.',
	'This version of the character is from a Mad Max-style post-apocalyptic future.',
	'This version of the character has a very short attention span and is easily distracted even mid-sentence.',
	'This version of the character has really bad memory and often forgets what they were saying mid-sentence.',
	'This version of the character has no sense of humor and doesn\'t understand jokes.',
	'This version of the character has no manners and is very rude.',
	'This version of the character is very polite and always uses "please" and "thank you".',
	'This version of the character is very polite and always uses "sir" and "ma\'am".',
	'This version of the character has a very short temper and gets angry easily.',
	'This version of the character is very calm and never gets angry.',
	'This version of the character is very shy and doesn\'t talk much.',
	'This version of the character is very confident and always speaks with authority.',
	'This version of the character is very insecure and always apologizes for everything.',
	'This version of the character is very insecure and always asks for reassurance.',
	'This version of the character is very egotistical and always talks about how great they are.',
	'This version of the character speaks as if they\'re very drunk.',
];
